import './globals.css'
import type { Metadata } from 'next'
import Navbar from '@/components/layout/navbar'
import { Inter } from 'next/font/google'
import * as React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    {/*
      <head /> will contain the components returned by the nearest parent
      head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
    */}
    <title>Rizkeeps</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <body className='bg-blackbg ${inter.className}  bg-no-repeat'>
      <Navbar/>
      {children}
    </body>
  </html>
  )
}
